Repository devcombine/devcombine, pull requests merged in 2023-05, with the labels that each got.

#24 feat : signup, login, logout 구현
  config/urls.py
  courses/admin.py
  courses/forms.py
  courses/models.py
  courses/templates/login.html
  courses/templates/signup.html
  courses/tests.py
  courses/views.py
Labels: 🪣 백엔드

#25 Feature/#8 ujeongoh
  courses/templates/courses/detail.html
  courses/templates/courses/index.html
  static/css/argon-dashboard.css
  static/img/logo_blue.png
  static/img/logo_white.png
  templates/base_detail.html
  templates/base_index.html
  templates/navbar.html
  templates/sidebar.html
Labels: 🛠️ 수정, 🌈 프론트

#38 Feature/#37
  api/__init__.py
  api/admin.py
  api/apps.py
  api/migrations/__init__.py
  api/models.py
  api/tests.py
  api/views.py
  courses/admin.py
  courses/migrations/0001_initial.py
  courses/models.py
  courses/views.py
Labels: 🛠️ 수정

#41 Feature/app
  courses/admin.py
  courses/migrations/0002_course_dislikes_course_likes.py
  courses/migrations/0003_course_update_at_alter_course_description_and_more.py
  courses/models.py
  series/admin.py
  series/migrations/0003_series_create_at.py
  series/migrations/0004_alter_series_create_at.py
  series/models.py
  series/views.py
  templates/base_detail.html
  templates/base_index.html
Labels: 🪣 백엔드, ⚙️ 세팅

#43 Feat/#42
  config/settings.py
  courses/models.py
  courses/tag_mapping.py
  courses/views.py
Labels: 🪣 백엔드

#45 fix : redirect 수정
  account/views.py
  courses/templates/admin/upload_success.html
Labels: 🌈 프론트

#48 feat : 태그에 페이지네이션, 검색 적용
  courses/templates/courses/index.html
  courses/views.py
  templates/sidebar.html
Labels: 🌈 프론트, 🪣 백엔드

#47 Feature/#13
  series/models.py
  series/templates/series/index.html
  series/templates/series/series_course.html
  series/urls.py
  series/views.py
Labels: 🪣 백엔드

#49 design: courses, series UI 수정
  courses/templates/courses/index copy.html
  series/templates/series/index.html
  templates/sidebar.html
Labels: 🛠️ 수정, 🌈 프론트

#53 design: series 화면 및 nav bar 링크 추가
  courses/templates/courses/index copy.html
  series/templates/series/index.html
  templates/navbar.html
Labels: 🛠️ 수정, 🌈 프론트

#55 feat : 태그 필터 보여주기 추가
  courses/templates/courses/index.html
  courses/views.py
Labels: 🛠️ 수정, 🌈 프론트

#58 fix : index 합치기
  courses/templates/courses/detail_test.html
  courses/templates/courses/index copy.html
  courses/templates/courses/index.html
  courses/templates/courses/index_test.html
Labels: 🛠️ 수정

#62 Feat/#51
  courses/admin.py
  courses/migrations/0002_category_categorytag_category_tags.py
  courses/models.py
  courses/views.py
  templates/sidebar.html
Labels: 🪣 백엔드

#63 feat : SeriesCourse Pagination 적용
  series/templates/series/series_course.html
  series/views.py
Labels: 🪣 백엔드

#65 fix : tag 검색 삭제, like 기능 수정
  courses/templates/courses/index.html
  templates/sidebar.html
Labels: 🐞 버그, 🛠️ 수정, 🔨 리팩토링, 🪣 백엔드

#69 design : Series 상세 페이지 페이지네이션 적용
  courses/templates/courses/index.html
  series/templates/series/series_course.html
  series/views.py
  templates/sidebar.html
Labels: 🌈 프론트

#71 Feat/category
  config/settings.py
  courses/admin.py
  courses/templates/admin/category/category_change_list.html
  courses/urls.py
  courses/views.py
  requirements.txt
Labels: 🛠️ 수정, 🪣 백엔드

#74 Feat/add crawling
  .gitignore
  crawling.py
  requirements.txt
Labels: 🪣 백엔드

#78 design : 로그인, 회원가입 페이지
  account/forms.py
  account/views.py
Labels: 🌈 프론트
